message:
  # if player don't have huskhomessign.use
  no-use-permission: "&cYou don't have permission to use warp signs."
  # if the warp name on the sign can't teleport
  invalid-warp: "&cCan't find this destination."
  # if HuskHomes can't teleport player to destination
  teleport-error: "&cError happened while teleporting you to this destination. Error details have been printed to the console"
  # if player don't have huskhomessign.break
  no-break-permission: "&cYou don't have permission to break warp signs."
# ------
# Sign creation and display settings
# ------
sign:
  # Settings about how to create a warp sign: (If player has huskhomessign.create)
  create:
    # If a new sign placed with following key word,
    # we will convert this sign to a warp sign.
    # Line's range is between 1-3, the line next to key word
    key-word: "[warp]"
    key-word-line: 1
  # Settings about how a valid warp sign look like
  # PS: If player don't have huskhomessign.create, they can't write key-word too.
  use:
    key-word: "&1[Warp]"
    key-word-line: 2