name: HuskHomesSign
version: '${project.version}'
main: ink.magma.huskhomessign.HuskHomesSign
api-version: 1.18
depend: [ HuskHomes ]
authors: [ MagmaBlock ]
description: A addon for HuskHomes to allow teleport by using a sign
commands:
  huskhomessign:
    usage: "/huskhomessign reload"
    permission: "huskhomessign.admin"
permissions:
  huskhomessign.admin:
    default: op
    description: Allows the player to reload the config
  huskhomessign.create:
    default: op
    description: Allows the player to create a warp sign
  huskhomessign.break:
    default: op
    description: Allows the player to break a warp sign
  huskhomessign.use:
    default: true
    description: Allows the player to use a warp sign
